### ISSUE TITLE
Check Fails with AttributeError: 'NoneType'

### ISSUE THREAD

**Issue by Nikhil-Singhal-06** [boschresearch/ros_license_toolkit#57]
Hi,

After updating to the latest release (1.3.0), the check process fails consistently after executing the `LicenseTextExsistCheck`  step.

![error-ros-license-toolkit](https://github.com/boschresearch/ros_license_toolkit/assets/87761277/e26b4f68-b0a3-4c4e-ad83-1179c66163e6)

**Comment by ct2034** [comment]
Thanks for the issue. We will look into  this
________________________________
From: Nikhil ***@***.***>
Sent: Thursday, March 14, 2024 4:47:16 PM
To: boschresearch/ros_license_toolkit ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [boschresearch/ros_license_toolkit] Check Fails with AttributeError: 'NoneType' (Issue #57)


Hi,

After updating to the latest release (1.3.0), the check process fails consistently after executing the LicenseTextExsistCheck step.

error-ros-license-toolkit.png (view on web)<https://github.com/boschresearch/ros_license_toolkit/assets/87761277/e26b4f68-b0a3-4c4e-ad83-1179c66163e6>
